### ISSUE TITLE
System requirements for Ubuntu

### ISSUE THREAD

**Issue by markvanderloo** [r-spatial/sf#1082]
1. The `README.md` can be updated. On an 18.04 Ubuntu box, you can do

```bash
sudo apt install libdgal-dev libudunits2-dev
```
and `sf` will install without problems (GEOM and PROJ will come with `libgdal-dev`). This means there is no need for users to add an unstable ppa to their `/etc/apt/sources.list`, which is comforting for sysadmins. 

2. Please mention the Ubuntu version for which the installation command is valid (or at least on what version that a particular `apt install` command was tested).

3. It would be nice to update the `DESCRIPTION` file with the exact library names that need to be installed. See [V8](https://cran.r-project.org/package=V8) or [curl](https://cran.r-project.org/package=curl) for some examples on how to make the `SysRequirements` field a little more helpful.

Cheers,
Mark

**Comment by edzer** [comment]
Thanks!
1. Have you tested on 16.04, which is EOL 2021? We list all packages to make clear for which package we need the header files; `sf` uses header files of GDAL, GEOS and PROJ. The PPA is recommended for everyone, because it brings more recent versions; ubuntu repos have been many years behind.
2. The implicit assumption is latest LTS with the PPA, but making hard statements here would require continuous testing (which, for instance, travis CI does)
3. Well, yes, that is a matter of taste. I believe r-hub tries to parse this field.

**Comment by markvanderloo** [comment]
1. and 2. Good point. Just tesded it on  16.04 laptop and it says that `libgdal` is not found, so you still need the 'unstable' ppa for that. So maybe add the 18.04 as a second Ubuntu option in the README?

On 3. 
Oh nice I did not know that `rhub` tries to parse it. If `rhub` recommends some standardization there that would be great. The thing is that the names of packages to install are not always obvious. For example for `rgl` you need `opengl`, but the package names are `libgl1-mesa-dev` and `libglu1-mesa-dev`. So I'd prefer the 'systematic name' (so to speak) over the 'trivial name'.
