### ISSUE TITLE
Error in CPL_read_ogr

### ISSUE THREAD

**Issue by NoushinN** [r-spatial/sf#1087]
Any ideas why this error happens?
I am using the sf library to read a .shp file..appreciate any help!

`Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Open failed.`

**Comment by edzer** [comment]
Please provide a reproducible example.

**Comment by NoushinN** [comment]
thank you, did you want more info? 
![image](https://user-images.githubusercontent.com/37668936/59780573-13a33900-926f-11e9-97ea-44eaf6c08341.png)

**Comment by edzer** [comment]
Maybe load library `sf` first, so that `%>%` also works?

**Comment by adrfantini** [comment]
The error you see in those screenshots (sigh) is related to the fact that the function `%>%` cannot be found. Load `sf`, `dplyr` or `magrittr` to get it.

Also, when providing a reproducible example you should also provide your input data. Otherwise it is hardly _reproducible_, is it?

**Comment by NoushinN** [comment]
thank you both, it doesn't seem to be a matter of loading libraries as they are loaded, I include them every time with the two columns (e.g. here::here()) because there seems to be conflicts between packages (e.g. here with lubridate)
here's a repress of the larger workflow:
![image](https://user-images.githubusercontent.com/37668936/59805864-58e35d00-92a7-11e9-9261-4363a076194a.png)

**Comment by rsbivand** [comment]
Please provide a real example. Also try not using `here::here()`, I guess that the fact that a shapefile is actually at least three files is confusing for **here**. I installed **here**, and tried to set it to:

```
library(sf)
here::set_here(system.file("shapes", package="spData")[1])
file.exists(file.path(system.file("shapes", package="spData")[1], ".here")) # TRUE
col <- st_read(here::here("columbus.shp")) # failed
# looks in /home/rsb
col <- read_sf(here::here("columbus.shp")) #failed
# looks in /home/rsb
col <- read_sf(system.file("shapes/columbus.shp", package="spData")[1]) # succeeded
col <- st_read(system.file("shapes/columbus.shp", package="spData")[1]) # succeeded
wrld <- read_sf(here::here("world.gpkg")) # failed
# looks in /home/rsb
wrld <- st_read(system.file("shapes/world.gpkg", package="spData")[1]) # succeeds
```
So, don't use **here**, not fit for purpose. I have removed **here**, a classic case of breaking the "as simple as possible, but not more so" rule.

**Comment by etiennebr** [comment]
Thanks for taking the time to report your issue @NoushinN. It seems your issue is very specific to the data you are reading and your computer configuration (OS, installation, packages available, ...). For that reason, to understand the root of your problem, we'd need public data (provide a URL, for instance) with which you can reproduce that error. There are [multiple causes](https://github.com/r-spatial/sf/issues?q=is%3Aissue+CPL_read_ogr+is%3Aclosed) ranging from missing file/wrong path to more complex.

Also, rather than post screenshots of your example, you can simply copy and paste the text generated by the reprex package. You can [embed code directly in your github post](https://guides.github.com/features/mastering-markdown/) (just like you did in your initial post), and include your session info. If you're new to reprex, it's worth having a [look at examples](https://reprex.tidyverse.org/articles/articles/learn-reprex.html).

**Comment by NoushinN** [comment]
@rsbivand and all
Thank you for your comments and help. Realizing that the here() package in combination with sf() to read the .shp files from a shp-input-folder was the issue, problem is solved now by specifying file.path and then reading .shp file.

**Comment by pecard** [comment]
I'm having the same problem with `Error in CPL_read_ogr` combined with `SEC_E_MESSAGE_ALTERED ` that is appearing after reading a few lines from the wfs service.

```
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  No layers in datasource.
In addition: Warning messages:
1: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 1: schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - A mensagem ou assinatura fornecida para verificação foi alterada
2: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 1: schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - A mensagem ou assinatura fornecida para verificação foi alterada

```
**reprex**
```
library(sf)
library(XML)
library(dplyr)
library(tabulEIA)

base_url <- "http://www.flora-on.pt"
endpoint <-"wfs"
q <- list(request = "GetCapabilities")
res <- httr::GET(url = httr::modify_url(base_url, path = endpoint), query = q)
res$url

txt <- httr::content(res, type = "text")
xml <- xml2::read_xml(txt)
doc <-  xmlParse(xml)
xmldf <- xmlToDataFrame(nodes = getNodeSet(doc, "//FeatureType"))
df <- xmlToDataFrame(nodes = xmlChildren(xmlRoot(doc)[["FeatureTypeList"]]), stringsAsFactors = F)

sflist <- list()
for(i in df$Name[1:100]){
  qf <- list(request = "GetFeature", typeName = i)
  file <- tempfile(fileext = ".gml")
  try(httr::GET(url = base_url, path = endpoint, query = qf, httr::write_disk(path = file)))
  spfloraon <- sf::read_sf(file)
  if(nrow(spfloraon) != 0){
    spfloraon <- spfloraon %>% st_set_crs(32629) %>% select(2, 3, 6)
    sflist[[i]] <- spfloraon
    }
  Sys.sleep(1)
}

```

**Comment by etiennebr** [comment]
Hi @pecard 

Thanks for this report. I suggest you open a new issue for your specific case and link to this issue, since this one is closed. Could you include the output from `sf::sf_extSoftVersion()` and `devtools::session_info()` or `sessionInfo()` and tell us where the error happens exactly (what's the value of `i`). I could not reproduce your bug by running your reprex (It works for me with the latest `sf` version on ubuntu). I know it's not helping much, but at least it tells us it's a problem specific to your system.

If you can, try to strip as much code as you can from your reprex, it will make it easier to find the exact cause. For example, maybe there's one file that fails, so you can just provide the code for this one file rather than the complete loop.
