### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by scdub** [r-spatial/sf#1191]
I see from the recently closed #1189 that there isn't a plan to continue providing releases via GitHub, but would it be possible to continue adding tags for the releases against the specific commits that went into those releases? This is helpful in packaging contexts where the version is built from source against a specific hash (and ideally a specific release).

**Comment by rsbivand** [comment]
Please accept that maintainers of CRAN packages support packages released through CRAN. If you install source packages from github, you risk magnifying revdep checks, because you are likely to find infelicities in unreleased work in process of development. Unless you are actually contributing to development (you have no affiliation nor any github activity in any spatial packages), simply install souurce from CRAN and ignore github, which is for development not release.

**Comment by edzer** [comment]
I agree: this is all overhead, double work, and subject to error. If you want a particular release, grab it from CRAN.
