### ISSUE TITLE
PROJ 6, post-proj4string sf, and PostGIS 3

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1234]
@etiennebr have you had time to look at [Postgis 3](http://blog.cleverelephant.ca/2019/02/proj4-postgis.html) support for PROJ6? Since `sf` is also moving towards using wkt rather than proj4strings, some work is needed on the PostGIS interface side. This work is done in the `SetFromUserInput` branch of sf; I currently switched PostGIS off entirely on travis, to get it pass.

**Comment by edzer** [comment]
@etiennebr have you had a chance to look at PostGIS 3.0.0, and how it handles non-proj4string CRS?

**Comment by etiennebr** [comment]
Sorry, I'm catching up and missed that mention. I worked on postgis 3 interface a bit to get it working on travis, but haven't taken the time to look in-depth at srid management. I'd like to do it in the next few weeks, depending on the level of work involved and my availability. At least get the tests to pass on travis-ci. I did not noticed you had to stop that part.

Is the branch [SetFromUserInput](https://github.com/r-spatial/sf/tree/SetFromUserInput) the right place to understand how proj will be implemented? I'll make sure to chek it out.

**Comment by edzer** [comment]
Thanks; yes, it is. New style `crs` objects now have to fields: `input` with whatever the user initialised the crs with (if anything: unspecified if reading an external source) and `wkt` with the WKT or WKT2 (GDAL >= 3) information. I think postgis 3 can now also work with WKT fields instead of proj4strings. `st_crs(4326)$epsg` still gives you back the epsg, if present, or else `NA`.

**Comment by etiennebr** [comment]
@edzer, I'm making good progress, however the new crs implementation makes it hard to track srid (or epsg). Any idea how we could synch srid that aren't available locally but are available remotely?

There used to be an `$epsg` element, but it disappeared. So I tried to force the `$input` to be `"EPSG:{remote_srid}"`, but `CPL_crs_parameters` won't return it (probably because it validates against the local list of crs). I'll dig a bit more in `CPL_crs_parameters`, but if you have any idea, let me know.

**Comment by edzer** [comment]
There is now a `$.crs` method that extracts the epsg from the WKT (if there is any):
```r
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
> st_crs('EPSG:4326')$epsg
[1] 4326
```

**Comment by etiennebr** [comment]
Thanks! The thing is there isn't a `$<-.crs` because the parameters are computed on the fly. I need to replace this old code:
``` R
crs <- st_crs(4326)
crs$epsg <- 900914
```
To create invalid local crs (I know it sounds weird), to track the id on the database side, because that's still how postgis tracks projections.

**Comment by etiennebr** [comment]
I resolved pretty much all issues, but it is still difficult to synchronize projections because missing wkt/srids are assumed to be 0 and the authority name and srid are fetched from the local database every time.

https://github.com/r-spatial/sf/blob/e23243bf39fed8e47dd35824f34ff431906c46b3/src/wkb.cpp#L684-L688

I'm thinking of a few solutions:
- track srid in the crs object instead of searching for a local srid (requires to slightly modify the crs implementation, e.g. [`epsg_from_crs`](https://github.com/r-spatial/sf/blob/e23243bf39fed8e47dd35824f34ff431906c46b3/src/gdal.cpp#L259-L268)) 
- override geometry columns srid in the database after write (`st_setsrid`) (hacky, simple, might be slow on large data) -- I think I'm going to implement this, just to have the tests pass in the short term.
- Raise error if we can't synch crs

I hope you're safe. Let me know if you have any thoughts.

**Comment by edzer** [comment]
Great work, @etiennebr !
