### ISSUE TITLE
Print missing dependencies when install fails

### ISSUE THREAD

**Issue by steffen-stell** [r-spatial/sf#1276]
I installed sf today on Fedora, but it failed at first because of missing dependencies. While other packages print the needed dependencies for the common Linux distros, it did not happen with sf. Instead it printed the less helpful message:
`configure: error: gdal-config not found or not executable`

It did not take that long to find the solution at the sf homepage, but it also wasn't the first hit on Google: 
```
sudo dnf install gdal-devel proj-devel proj-epsg proj-nad geos-devel udunits2-devel
```

Iit would definitely be more convenient, if sf could do what other packages do and tell you directly.

**Comment by edzer** [comment]
Feel free to contribute!

**Comment by rsbivand** [comment]
And note that installing (very) outdated versions available for Centos/RHEL/Fedora is really not to be encouraged. Not only are many bugfixes present in current versions of GDAL, GEOS and PROJ, but also a different and probably more accurate system for coordinate operations. Easy is here the wrong goal - install from source if possible.

**Comment by Robinlovelace** [comment]
Interesting to see this thread, agree that the error message if the install message fails should include install instructions. I recall seeing excellent instructions to install dependencies in packages by @jeroen that were really useful. See [here](https://github.com/ropensci/magick/blob/bf02587a2e667a0266683601d592702437324d7b/configure#L70-L90) for an example of messages that appear if you execute the following command without upstream dependencies:

```r
install.packages("magick")
```

I guess that including something like the following in the `configure` file would fix this issue, taking into account the need to install more up-to-date versions:

```bash
# Customize the error
if [ $? -ne 0 ]; then
  echo "--------------------------- [ANTICONF] --------------------------------"
  echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
  echo " - deb: $PKG_DEB_NAME (Debian, Ubuntu)"
  echo " - rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
  echo " - csw: $PKG_CSW_NAME (Solaris)"
  echo " - brew gdal@6 (MacOS)"
  echo "For Ubuntu versions Trusty (14.04) to Bionic (18.04) use the PPA:"
  echo "   sudo add-apt-repository -y  ppa:ubuntugis/ubuntugis-unstable"
  echo "   sudo apt-get update"
  echo "   sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev "
  echo "-------------------------- [ERROR MESSAGE] ---------------------------"
  cat configure.log
  echo "--------------------------------------------------------------------"
  exit 1
fi
```

I would put in a PR but am intimidated by the size of https://github.com/r-spatial/sf/blob/master/configure

**Comment by rsbivand** [comment]
Right, for Debian, depending on target level and chosen repo, you will get wildly varying versions of GDAL and PROJ. For rpm, it is even worse, as recent PROJ and GDAL versions simply are not there at all. Users do need to take full responsibility for handling installs of upstream software at least until the violent convulsions presently occurring are calmed. Each lab needs to document its policy, and transition policies - we cannot reasonably decide for users what is best for their needs. We see this when CRAN auto-updates Debian and suddenly breakages happen.

**Comment by Robinlovelace** [comment]
Isn't the advice below pretty future proof, especially with the imminent release of Ubuntu 20.04 LTS and Ubuntu a common Linux distro for R-spatial users? No comment on the situation for Fedora but I guess you and @Nowosad will be able to provide sensible advice (the current advice being 'compile from source' by the sounds of it):

#### Ubuntu
Dependencies for recent (non-LTS, later than bionic) versions of Ubuntu are available in the official repositories; install them with
```sh
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
```

To install the dependencies on LTS versions of Ubuntu (xenial, bionic), either add [ubuntugis-unstable](http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu/) to the package repositories and use:
```sh
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
```
or install dependencies from source; see e.g. an older [travis](https://github.com/r-spatial/sf/blob/593ee48b34001fe3b383ea73ea57063ecf690732/.travis.yml) config file for hints.

#### Fedora
The following command installs all required dependencies:
```sh
sudo dnf install gdal-devel proj-devel proj-epsg proj-nad geos-devel udunits2-devel
```

Maybe the README should be updated.

**Comment by edzer** [comment]
@Robinlovelace that is what the README says. The OP was just annoyed that the first google hit did not give the answer. What Roger tries to say is, I believe, that even distribution maintainers get it "wrong" these days, by either being entirely outdated (rhel) or combining versions that don't match (debian/ubuntu). If you look at the `configure.ac` files of `rgdal` or `sf` you'll notice we try to cope with quite a variety of complex cases, and constantly have to adapt to change. Help is certainly welcome also here, especially from those willing to understand the complexity and willing to maintain solutions.

**Comment by Robinlovelace** [comment]
Thanks for the clarification @edzer. I've never looked at `configure` files before and have little knowledge of the levels of compatibility between spatial packages packaged by different distributions, but think that the advice in the README for Ubuntu 18.04 is good and future-proof. If that advice can be communicated directly in cases where the install fails I see no downside, but am not sure how to do that, despite having looked at the example from the `magick` package.

Out of interest which versions of GDAL/PROJ on Debian don't match? I've found no issues using the `ubuntugis-unstable` PPA and am hoping that on the next LTS version of Ubuntu the versions in the default repo will work. Really hoping, because that is the computer set-up that I recommend to people who want to switch to Linux. I know that giving 'wrong' advice can be giving no advice, but giving some advice can be better than giving no advice, especially for beginners who need the most help. A balance of course. Hope that is helpful.

**Comment by edzer** [comment]
Debian came at some stage with GDAL 2.x and PROJ 6.x, which is a combination one shouldn't try (but compiled nevertheless..) On Ubuntu the upgrade from GDAL 2.x to 3.x didn't work, but needed a remove + reinstall to get rid of stale files - IIRC you were also bitten by this.

**Comment by Robinlovelace** [comment]
> On Ubuntu the upgrade from GDAL 2.x to 3.x didn't work, but needed a remove + reinstall to get rid of stale files - IIRC you were also bitten by this.

Likely was, see your point and fair to assume that it will happen again. Hopefully that was just a one-off/temporary issue and that the current and future versions are compatible.

**Comment by rsbivand** [comment]
I think hard-won experience shows that hope needs to be buttressed by checking key upstream components before they even get to release candidates, and working with them to smooth out infelicities and differing conceptualisations. You'll see a number of interventions from us, including Brian Ripley, over the years. Most recently https://github.com/OSGeo/PROJ/pull/1967 based on https://lists.osgeo.org/pipermail/proj/2020-February/009405.html, but there are lots of others over the last 15 years or so. The **rgdal** R and C code looks like a battlefield, with lots of `#ifdef` and other conditions around version changes, and oddities in upstream source release packaging; **sf** has fewer, because it hasn't been scarred as much. However, without help from upstream developers who take a generous interest in what we do, we couldn't keep things running. Thanks, @rouault and others!

**Comment by rsbivand** [comment]
See https://lists.osgeo.org/pipermail/gdal-dev/2020-February/051716.html and thanks to @manisandro https://src.fedoraproject.org/rpms/gdal/pull-requests

**Comment by Robinlovelace** [comment]
> without help from upstream developers who take a generous interest in what we do, we couldn't keep things running

Huge thanks to them, and r-spatial developers, for keeping the show on the the road and insulating users from upstream changes about which they can be blissfully unaware!
