### ISSUE TITLE
calculate distance from point inside polygon to nearest edge of polygon

### ISSUE THREAD

**Issue by brfitzpatrick** [r-spatial/sf#1290]
st_distance returns a value of zero for the distance between a point within a polygon and the edge of that polygon. Is there a way to calculate the distance between a point within a polygon and the nearest point on the edge of this polygon? 

I thought perhaps of converting the (edge of the) polygon to a line of some sort and calculating the shortest distance between the point and this line but I'm having trouble with the conversion.

**Comment by edzer** [comment]
Yes, use `st_cast` to convert to linestring, then `st_distance` sounds like the right way.

**Comment by brfitzpatrick** [comment]
Yes, that works, thank you.

` 
st_geometry(obj = polygon.sf) %>%
    st_cast(to = 'LINESTRING') %>%
      st_distance(y = point.sf)
`

**Comment by edzer** [comment]
> I tried st_cast to convert polygons to multilinestring and then calculate distance, but that dind't work.

What do you mean by "didn't work"? Did you directly cast to `MULTILINESTRING`?

**Comment by fernandabiologia** [comment]
Thanks for replying and I'm sorry I wasn't clear. After posting I kep trying and I think the issue was actually with my spatial vector data. It was giving me 3 measurements per point, when I expected to get one. 
e.g. 
![image](https://user-images.githubusercontent.com/7490621/227388659-67e99e1b-e5cc-4dd3-a213-f6796966705c.png)

Then I tried with another vector data and it worked just fine:

dist_for_edge <- st_geometry(obj = polygons_sf) %>% 
  st_cast(to = 'MULTILINESTRING') %>%
  st_distance(y=points_sf)
