### ISSUE TITLE
st_make_valid causing errors as it transitions from lwgeom to sf

### ISSUE THREAD

**Issue by skhaji** [r-spatial/sf#1300]
I am creating a package (github.com/EdBuild/edbuildmapr) that uses st_make_valid.  I am getting the following warnings in the winbuilder checks:
Warning: replacing previous import 'lwgeom::st_make_valid' by 'sf::st_make_valid' when loading 'edbuildmapr'
Warning: replacing previous import 'sf::st_make_valid' by 'lwgeom::st_make_valid' when loading 'tmap'

On my computer, I have updated GEOS to 3.8.1, and sf to 0.9.0 so that I can use the sf::st_make_valid but I hesitate to require a version of sf that is only available via github and not on CRAN.  Can you advise as to how I can call st_make_valid without warnings?  I get warnings whether I use lwgeom::st_make_valid or sf::st_make_valid.

Thanks for your help!

**Comment by rsbivand** [comment]
Had you considered Suggest'ing rather than Import'ing **tmap**? Or only import the functions you actually use (the same applies to **spdep**). If you import selectively, you may be able to keep **tmap** in Imports without it warning you that it doesn't like the same function appearing in **sf** and **lwgeom** as released. Importing only selected functions also simplifies the search space (only used at foot of `R/sd_map.R`, `R/sd_neighbor_map.R`). **tmap** is trying to protect you against malformed geometries - since the input data seem to be pulled from the cloud, you could make sure that they are well-formed first. You should further *never* use `utils::globalVariables()`, it is very fragile. Find out what you are doing that annoys `check --as-cran` and fix that. Finally, modularisation is always a good thing, and much code seems to be copy&paste, so will need fixing in multiple places if it breaks.

**Comment by skhaji** [comment]
Thanks for your reply and taking the time to look through our package.  We're going to import selectively and see if that removes the warnings.  We'll update you after our checks.

**Comment by skhaji** [comment]
Importing tmap , spdep, and lwgeom selectively works and allows us to pass the winbuilder tests.  Thanks!

**Comment by rsbivand** [comment]
Thanks for trying this out! Your results will be very useful for others too!

**Comment by edzer** [comment]
Upcoming `lwgeom` will no longer provide the `st_make_valid` generic.
