### ISSUE TITLE
tidyverse::*_join returns different results depending on the order of the parameters

### ISSUE THREAD

**Issue by gabrielmagno** [r-spatial/sf#1391]
## Example dataset
```r
library(sf)
library(tidyverse)

set.seed(42)

nc_sf <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

nc_df <- data.frame(
  CNTY_ID     = nc_sf$CNTY_ID,
  choosen_one = sample(c(TRUE, FALSE), nrow(nc_sf), replace=TRUE)
)
```

## Problem

This will work:
```r
nc_sf %>%
  left_join(nc_df, by="CNTY_ID") %>%
  ggplot() +
  geom_sf(aes(fill=choosen_one))
```
![Rplot](https://user-images.githubusercontent.com/244890/81619333-bdc40c00-93bf-11ea-8a4a-2b24e7ad81a4.png)

This will not work:
```r
nc_df %>%
  right_join(nc_sf, by="CNTY_ID") %>%
  ggplot() +
  geom_sf(aes(fill=choosen_one))
```
Gives: `Error: stat_sf requires the following missing aesthetics: geometry`

Even if I explicitly puts the geometry in the aes, it will not work
```r
nc_df %>%
  right_join(nc_sf, by="CNTY_ID") %>%
  ggplot() +
  geom_sf(aes(geometry=geometry, fill=choosen_one))
```
Gives: `Error in if (type == "point") { : argument is of length zero`

## Expected behaviour

Is this the expected behavior or there is a bug? 

My intuition would expect that `left_join(a, b)` have the same semantics and should return the same result as `right_join(b, a)`.

## Tests

I noticed that the object returned by `left_join` and `right_join` are different.
The first command, with `lef_join`, returns both the `sf` and `data.frame` objects. The second command, with `right_join`, returns only the `data.frame` object.
I tested a couple of function calls, changing the order of the parameters and also using the base `merge` function.
```r
left_join(nc_sf, nc_df, by="CNTY_ID") %>% class # works, returning `sf` and `data.frame`
right_join(nc_sf, nc_df, by="CNTY_ID") %>% class # works, returning `sf` and `data.frame`
left_join(nc_df, nc_sf, by="CNTY_ID") %>% class # does not work, returning only the `data.frame`
right_join(nc_df, nc_sf, by="CNTY_ID") %>% class # does not work, returning only the `data.frame`
merge(nc_sf, nc_df, by="CNTY_ID") %>% class # works, returning `sf` and `data.frame`
merge(nc_df, nc_sf, by="CNTY_ID") %>% class # does not work, returning only the `data.frame`
```

## Conclusion
Merge/join functions will work only if the `sf` object is the *first* parameter of the function call, no matter if it is a left join or right join.

## System Environment
Library versions:
```
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.0     ✔ purrr   0.3.4
✔ tibble  3.0.1     ✔ dplyr   0.8.5
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
> 
```

**Comment by tzoltak** [comment]
This simply can't work because of how S3 classes work in general in R. Method dispatch is based only on the first argument and consequently:

- if you call `left_join(sf_object, data_frame_object)` a method for `sf` objects is dispatched, that treats `sf` object properly and returns `sf` object;
- if you call `right_join(data_frame_object, sf_object)` a method for `data.frame` objects is dispatched, that doesn't care at all about `sf_object` is somewhat special and returns regular data frame (to be precise a `tibble`).

**Comment by hadley** [comment]
@tzoltak that's true, but not complete — in dplyr, we certainly could choose to implement double dispatch so that `left_join(x, y)` and `right_join(y, x)` return the same type of thing, but we deliberately chose not to. 

We did this partly because getting all the details requires a complicated algorithm (so it's much harder to explain than returning the same type as the left-hand side), and partly because it's not obvious what you should get if you (say) join a sf and a data table, or a data table and a grouped df, or ...
