### ISSUE TITLE
no sf geometry features recognised by R

### ISSUE THREAD

**Issue by Molly-Scott** [r-spatial/sf#1421]
Hi there, I work with Windows 10. I have recently updated R4.0, RStudio(1.3.959) and RTools(40). Now none of my simple features or maps are working. I have installed rgeos, rgdal, sp, sf all from the source code below (please scroll down)

install.packages('rgeos', type='source')
install.packages('rgdal', type='source')
install.packages('sf', type='source')
install.packages('sp', type='source')

And get this output below
rgeos version: 0.5-3, (SVN revision 634)
 GEOS runtime version: 3.8.0-CAPI-1.13.1 
 Linking to sp version: 1.4-2 
 Polygon checking: TRUE 

rgdal: version: 1.5-10, (SVN revision 1006)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.0.4, released 2020/01/28
Path to GDAL shared files: C:/Users/Username/Documents/R/win-library/4.0/rgdal/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 6.3.1, February 10th, 2020, [PJ_VERSION: 631]
Path to PROJ shared files: C:/Users/Username/Documents/R/win-library/4.0/rgdal/proj
Linking to sp version:1.4-2
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading rgdal.
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
Loading required package: deldir
deldir 0.1-25

**Comment by Molly-Scott** [comment]
Here is a reproducible example of my code. FYI ggmap and geom_sf have worked perfectly together for me for a long time. Thank you in advance for your help

library(rgdal)
library(rgeos)
library(sf)
library(sp)
library(ggplot2)
library(leaflet)
library(mapview)

#with ggmap/ggplot
#create map
myLocation = c(-158.287, 21.21425, -157.676, 21.7337)
myMap = get_map(location=myLocation, source="google", maptype = "satellite")
ggmap(myMap)           

#dataframe of positions
df <- data.frame(Tag.ID=c(7917,7917, 7917,7918,7918,7918,7919,7919,7919),
                 Station.Name=c("FAD X", "FAD U", "FAD L", "GR5","Reef44", "Kbay", "HIMB", "R8", "R9"),
                 Num.Det=c(1, 5, 6, 5, 7, 90, 7, 55, 32),
                 Longitude=c(-157.9933, -157.8279, -157.7838, -158.1492, -157.8197, -157.7916, -157.7659, -157.7745, -157.7793),
                 Latitude=c(21.86333, 21.49908, 21.43453, 21.62387, 21.46288, 21.44778, 21.50943,  21.4972, 21.48997))
#convert to sf
df_sf <-  df%>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)                 

df_map <-
  ggmap(myMap) +
  coord_sf() +
  geom_sf(data = df, aes(size = Num.Det, color = factor(Tag.ID), fill = factor(Tag.ID)), shape=21, inherit.aes = F) +
  labs(x = "Longitude", y = "Latitude", color = "Tag ID", fill = "Tag ID", size = "Number of detections") +
  facet_wrap(~Tag.ID)                 

df_map    

 Error: stat_sf requires the following missing aesthetics: geometry            
              
# with mapview
sf_mapview <- 
  df_sf %>% 
  mapview(color = "white", alpha.region = 0, cex = 3, legend = F, homebutton = F, layer = "Station.Name", map.types = "Esri.WorldImagery")

sf_mapview

df_mapview <-
  (sf_mapview +
     mapview(df, zcol = "Tag.ID", cex = "Num.Det", burst = T, legend = F, homebutton = F))@map 

df_mapview

Error: 
oops! Arguments xcol and/or ycol are missing!
You probably expected df to be a spatial object. 
However it is of class data.frame. 
Either convert df to a spatial object or provide xcol and ycol.

**Comment by edzer** [comment]
For `geom_sf()`, the `data` argument must be an `sf` object, otherwise it has no clue _where_ the data are; try to insert
```r
df = st_as_sf(df, coords = c("Longitude", "Latitude"))
```
before the call to `ggmap` and `geom_sf()`.

**Comment by rgzn** [comment]
Hey @Molly-Scott, @Edzer is correct. However, just to clarify, you already created the `sf` object with this line 
`df_sf <- df%>%
st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)` 

So just make sure to use `df_sf` instead of the plain dataframe. 

Another tip: Try the [reprex](https://reprex.tidyverse.org) package for reproducible examples whenever posting bugs on here or on stackoverflow. Makes it easier for both the askers and the answerers.

**Comment by antaldaniel** [comment]
I just left this comment [here](https://github.com/tidyverse/ggplot2/issues/3936#issuecomment-646273883), and slightly re-formulate it. My answer replies only partly to the reported issue, because it does not have a repex, anyway, but I think that similar issues are plaguing now stackoverflow and github. 

I think that such issues will pop up in dplyr, ggplot2 and sf issues reports, because it is not a very good choice that   [sf::left_join.sf ](https://r-spatial.github.io/sf/reference/tidyverse.html) is overwriting the dplyr::left_join (and similarly rbind, cbind) functions.  I realized this because one of my package relies on sf an dplyr, too.    While I wanted to avoid importing the entire `sf ` package just for a join, I could not do otherwise, because the `left_join.sp` is not exported, and it relies on further dependencies that are not exported.  I find it a very bad idea that instead of creating a `spatial_left_join()` or just simply an exporting `left_join.sp` the the `dplyr::left_join` (and rbind, and cbind) functions are tempered with. 

Users should not be left with an impression that they can 'join'  spatial objects with non spatial ones, or they are inserting a non-spatial object to the place they are used to.  They cannot create a df as.data.frame or as.tibble, becuase they need the spatial dimension to work with sf.  A join or binding between a non-spatial and a spatial object is a bit illusory, too.  I understand that the aim was to create a well-known, familiar API UI, but I think that it creates more confusion than what it saves with using a familar UI.

Joining objects that have a spatial element or dimension is a separate problem than joining tables.  A different join is made, and a different object is returned.  I think that calls for a function that can be differectly references, interacted with.

**Comment by edzer** [comment]
try `?st_join`.
