### ISSUE TITLE
CRAN errors for sf & stars on win-gcc10-UCRT

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1629]
The new WIndows-UTF-8 toolchain, described [here](https://developer.r-project.org/Blog/public/2021/03/12/windows/utf-8-toolchain-and-cran-package-checks/),  causes errors that might be related to GDAL reading. These are hard for me to check, a win-builder is not yet in place. @jeroen a wild hypothesis: would this require new builds of GDAL for this toolchain? @rsbivand or @mdsumner any ideas what we could try out?

From here: https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/sf-00check.html
```
  Cannot open data source C:\msys64\home\tomas\ucrt3\svn\ucrt3\r_packages\pkgcheck\CRAN\sf\sf.Rcheck\sf\osm\overpass.osm
  Error in CPL_get_layers(dsn, options, do_count) : Open failed.
  Calls: print -> st_layers -> CPL_get_layers
  In addition: Warning messages:
  1: In CPL_get_layers(dsn, options, do_count) :
    GDAL Message 1: Cannot find osmconf.ini configuration file
  2: In CPL_get_layers(dsn, options, do_count) :
    GDAL Error 1: Could not parse configuration file for OSM import
```
and here: https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/stars-00check.html
```
> r = read_stars(system.file("nc/reduced.nc", package = "stars"))
trying to read file: C:\msys64\home\tomas\ucrt3\svn\ucrt3\r_packages\pkgcheck\CRAN\stars\stars.Rcheck\stars\nc\reduced.nc
Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver), :
  file not found
```
and
```
  > raw <- read_stars(system.file("nc/bcsd_obs_1999.nc", package = "stars"))
  trying to read file: C:\msys64\home\tomas\ucrt3\svn\ucrt3\r_packages\pkgcheck\CRAN\stars\stars.Rcheck\stars\nc\bcsd_obs_1999.nc
  Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver), :
    file not found
  Calls: read_stars ... is_big -> read_stars -> <Anonymous> -> CPL_read_gdal
```

**Comment by jeroen** [comment]
It's because @kalibera is overriding windows build the for ucrt with [this Windows.ucrt patch](https://www.r-project.org/nosvn/winutf8/ucrt3/patches/CRAN/sf.diff) but this does not include the gdal/proj data files as we do here:

https://github.com/r-spatial/sf/blob/0212fdc209aea03d7c97df7f2d1518bceceaca4a/src/Makevars.win#L27-L31

I think only @kalibera can fix this. But maybe one thing you could do is have a better diagnosis/error message when the proj/data files are not found where they are expected.

**Comment by rsbivand** [comment]
Curiously, **rgdal** seems to pass on this platform https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/rgdal-00check.html - it would be interesting to see the `00install.out` file for that run.

**Comment by kalibera** [comment]
The installation output output can be found here: https://www.r-project.org/nosvn/winutf8/ucrt3/CRAN/checks/gcc10-UCRT/export/rgdal.Rcheck/

**Comment by kalibera** [comment]
I've added copying of `gdal` and `proj` share also to `Makevars.ucrt`, thanks for spotting this. The new patch is [here](https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/r_packages/patches/CRAN/sf.diff). I will similarly fix patches for other packages.

The patches are to help package authors with adding support for the new toolchain, but of course at any time you can incorporate `Makevars.ucrt` (the file added by the patch) to your package code and adapt and maintain it yourself, I'd then just remove the patch.

`sf` is still not passing checks on my machine, but it maybe due to similar issues in other packages:

```
> if (sf_extSoftVersion()["USE_PROJ_H"] == "true" || sf_proj_info("have_datum_files")) {
+   "datum files installed"
+ } else {
+   "datum files not installed"
+ }
[1] "datum files installed"
>
> x0 = sp::CRS("+init=epsg:4326")
Error in sp::CRS("+init=epsg:4326") : NA
Execution halted
```

**Comment by jeroen** [comment]
@kalibera I think indeed, in this example `sp` calls out to `rgdal` which also requires the proj data files. I think the issue will be fixed once you rebuild rgdal including the proper `proj` data.

Be careful though that the version of the proj data in the package has to match the version of the static library.

**Comment by kalibera** [comment]
Yes, fixing this also in `rgdal` makes `sp` pass checks. Now there are still differences in outputs that may be important. To appear at next run of the checks. 

`$(LOCAL_SOFT)/share/proj` should be the correct directory, it is filled in when `proj` is built, so the same version.

**Comment by edzer** [comment]
Why, when copying all the data over, do we still see this in sf's [check](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/sf-00check.html)?
```
  Cannot open data source C:\msys64\home\tomas\ucrt3\svn\ucrt3\r_packages\pkgcheck\CRAN\sf\sf.Rcheck\sf\osm\overpass.osm
  Error in CPL_get_layers(dsn, options, do_count) : Open failed.
  Calls: print -> st_layers -> CPL_get_layers
  In addition: Warning messages:
  1: In CPL_get_layers(dsn, options, do_count) :
    GDAL Message 1: Cannot find osmconf.ini configuration file
  2: In CPL_get_layers(dsn, options, do_count) :
    GDAL Error 1: Could not parse configuration file for OSM import
```
The usual windows binary packages have it:
```
# unzip -l sf_0.9-7.zip | grep ini
     4879  2021-03-06 12:45   sf/gdal/osmconf.ini
```

**Comment by kalibera** [comment]
I've not re-run the checks yet. It will take 24h or so from now for the new results to appear.
