### ISSUE TITLE
st_as_grob error with dimnames

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#1678]
Something about the way `osmdata` names its coordinate matrices causes `st_as_grob` to error because it constructs very long names during a `do.call` `rbind` operation. Reported (by a user) and diagnosed (by me) here (with working example):

https://stackoverflow.com/questions/67525658/error-in-do-callrbind-x-with-qtm-and-openstreetmaps/67534125#67534125

I *think* that `osmdata` is giving its coordinates rownames or colnames by the OSM ID for the vertex, and this results in names bigger than R's 10,000 character limit.

Solution could be either for `osmdata` to not do this, or for `st_as_grob` methods to drop names from matrices before doing this.

**Comment by barryrowlingson** [comment]
This was discussed over on the osmdata package some time ago https://github.com/ropensci/osmdata/issues/188 

I don't think its really "fixed" since it seems possible to get st_as_grob to break by creating a matrix by other purposes, so a fix in `sf` might seem to be the place for it, unless there's an explicit documentation (and test) that states that constructing an sf object with names like this is invalid....

**Comment by edzer** [comment]
Yes, this is another case where @mpadge 's package creates so-called `sf` objects that break `sf` code. I don't see any point in doing that, nor in fixing the problem he causes here, and have argued over and over that users end up complaining here, where the problem lies in osmdata. One more data point.

**Comment by mpadge** [comment]
@edzer You are right to be frustrated here that people to unduly complain here for problems clearly caused by `osmdata`, and for that i can only apologise. I nevertheless maintain the the fix within that package, via the [`unname_osmdata_sf()` function](https://docs.ropensci.org/osmdata/reference/unname_osmdata_sf.html) is sufficient, and stop short of entire removal of rownames which would prevent people "complaining here," yet also destroy the functionality of the package. As @barryrowlingson indicates, R allows rownames on array objects, and so routines intended to accept array inputs should also deal appropriately with those objects regardless of attributes like rownames.

One solution here would be to modify this line:
https://github.com/r-spatial/sf/blob/eaee12189957935567f0249ae7c8ae5a3d6c7019/R/grid.R#L68
to:
``` r
get_l = function(x) unlist(sapply(x, function(y) vapply(y, nrow, 0L, USE.NAMES = FALSE)))
```
If rownames truly are no part of the `sf` representation, then that also ought to be explicitly enforced throughout through appropriate use of `USE.NAMES = FALSE` on all calls which otherwise default to presuming such. (The other calls in `grid.R` implicitly strip the rownames through the sub-setting - `[, n]`, so work okay regardless.)

**Comment by edzer** [comment]
Apologizing here does not help users getting stuck with so-called `sf` objects created by `osmdata` that don't work with the rest of the `sf` stack. You should call `unname_osmdata_sf` on all objects by default, and add an argument to **optionally** add names to objects, with the warning that object thus created have some advantages but will not work with the rest of the software that assumes unnamed stuff. I call your refusal of doing so intentional obstruction of interoperability. Your suggestions ignore the fact that S3 objects are defined implicitly by behavior, that `sf` objects are defined by package `sf` and all the packages using objects that **that package** creates, and that by solving this particular issue we just have to wait for the next one to pop up. Feel free to go through all code involved and suggest a complete PR, or create your own class and provide a conversion method that creates **proper** objects of class `sf`.
