### ISSUE TITLE
How to silence sf_use_s2?

### ISSUE THREAD

**Issue by MikkoVihtakari** [r-spatial/sf#1782]
Related to [this issue](https://github.com/r-spatial/sf/issues/1780), I need to add `sf::sf_use_s2(FALSE)` to a function to do cropping, and add `sf::sf_use_s2(TRUE)` once the cropping is done. This leads to the following print on console:

`Spherical geometry (s2) switched off
  |===========================================================================     |  93%Spherical geometry (s2) switched on`

In my opinion, the user does not need to know every time I switch s2 on or off. How to silence the print? `invisible(sf::sf_use_s2(FALSE))` does not seem to work.

**Comment by edzer** [comment]
This is intentional: as `sf_use_s2()` changes global behaviour for the user, the user needs to be informed. 

Of course you can hack it: see what it does, and do that without informing the user; alternatively, set `sink(/dev/null)` (or sth appropriate for your platform) and set it back, but that's rigorous!

We may need to find an alternative for cropping (i.e., add an argument), that does this inside the function, without warning, but clear from the calling code.

**Comment by MikkoVihtakari** [comment]
Why force the print? I'd just print a message instead. The user is informed in a similar way and one can avoid sink hacks to turn the message off. That said, I would not write a function, which modifies global behavior without telling the user. In this case, it's a temporary hack and s2 is switched back on afterward (should probably check whether s2 is on to begin with, though).

**Comment by rCarto** [comment]
I use something like that in `mapsf::mf_worldmap()`:
https://github.com/riatelab/mapsf/blob/8f6167dbc5aec46b593a3c8b7a9f3d2986d52542/R/mf_worldmap.R#L16

But a 'quiet=FALSE' or 'verbose=TRUE' default arg in `sf_use_s2()` would be nice.

**Comment by edzer** [comment]
Clever, but if that function breaks halfway, it will leave the R session of the user in a completely different mode than when it doesn't. It might be safer to set the s2 mode back with on.exit(), directly after setting it to the desired mode.

**Comment by rCarto** [comment]
Oh yes, I see that now.

**Comment by eliocamp** [comment]
R has a standard way of suppressing messages and warnings. `sf_use_s2()` should use `mesage()` instead of `cat()` and then the user can just use `suppressMessages(sf_use_s2(TRUE))`.

If the devs agree, I can open a PR with the change.

**Comment by edzer** [comment]
This is intentional: if your code switches off s2 usage, the user needs to be notified because it has consequences for anything they do subsequently with sf.

If you want to switch it of _temporarily_, I'd be more in favour of adding sth like
```
sf_without_s2_do(body) {
    # get current s2 setting, on.exit(this setting)
    # evaluate body
}
```
so that you can do your things without s2 by
```
sf_without_s2_do( { # do your things
} )
```
this would guarantee that you're not _invisibly_ modifying global behavior.

**Comment by eliocamp** [comment]
Yes, I understand the motivation of why printing a message. But my point is that said message should use the standard system that R has for sending message (`message()`) which is easy to suppress if needed with the standard `suppressMessages()` function without the need of any potentially buggy hack. In my case, I know very well that my code is changing global settings and I don't want the message printed in the final report.

**Comment by MikkoVihtakari** [comment]
I totally agree with @eliocamp. I see no reason why one should deviate from the standard and force something no matter how hazardous the consequences should be. If you like, use `warning()` instead of `message()`. Both can be suppressed. 

As a developer of `ggOceanMaps` I have grown tired of these forced messages. I pretty much need to wrap every second function from `sp`, `sf` or tidyverse in `suppressMessages(suppressWarnings())` to avoid cluttering the console of the user. Now adding the `sink()` hack on top of that (which I have done for some functions that use `cat()`) even more reduces the readability of the code. All this to get rid of the messages. Devs of important base packages should always offer a "silent" argument inside their functions.

**Comment by MikkoVihtakari** [comment]
Do you mean that something like the following is the safest way of suppressing the message in the current version of sf?

```{r}
s2_mode <- sf::sf_use_s2()
sink <- capture.output(sf::sf_use_s2(FALSE))
sink <- capture.output(on.exit(sf::sf_use_s2(s2_mode)))
```

**Comment by rsbivand** [comment]
@eliocamp In Rmd, use extra chunk arguments, such as `results='hide'`, after creating a separate chunk for `st_use_s2()`, since you as author are deciding  to mute the information and taking responsibility for that decision.
@MikkoVihtakari The same principle applies, but package authors using **sf** should avoid masking **sf** messages other than in documention of which you yourself are the author. If you mute anyway, your users will be misled and will not know why things are happening. I agree that a muting wrapper such as suggested by @edzer might be worth considering, but maybe in 6 months, once the use of **s2** has stabilized.

**Comment by MikkoVihtakari** [comment]
@rsbivand I doubt that an average user wants to know what is happening inside a function that plots a map. All they care about is that the map is correct and that they can plot their data on it. Muting things that get changed *temporarily* only makes sense for those users. It is not misleading the user. It is helping the user to focus on the essence. Advanced users can always dig into the code and see what happens.

**Comment by rsbivand** [comment]
Maybe they don't want to, but information is provided to alert users, some of whom have mission-critical applications, of ongoing changes that may impact their outcomes. If all they care about  is plotting data, but  not whether it is correctly positioned (GDAL barn-raising), they arguably should find something else to do. Not knowing one's tools is irresponsible. Helping the user to focus on "the essence" is imposing one narrative to the exclusion of others; users are much more varied than might be expected.

**Comment by MikkoVihtakari** [comment]
...exactly what you do by forcing messages with `cat()` instead of using `message/warning`.

**Comment by eliocamp** [comment]
We all agree that sf should inform the use of global changes, the question is just a technical issue of using cat() vs message(). 

I don't see what's the advantage of using cat() over, message(), which is the standard way that authors can send messages to the user. 
Messages printed with message() raise an appropriate condition, they are shown with a different colour in RStudio and can be suppressed with standard functions (there would be no need of a silent wrapper if sf_use_s2() used message(); just use suppressMessage()).

**Comment by rsbivand** [comment]
Yes, but if downstream package authors intervene, the end user does not see the message that they are intended to be exposed to. So there is an arms race to make it harder for proponents of the "easier than advisable" approach to mute information that infrastructure package maintainers feel that end users should see. In the last resort, it is the maintainers of the infrastructure packages who have to spend time debugging downstream packages for users confused by changes in outcomes. Colours in RStudio are strictly orthogonal.

**Comment by rsbivand** [comment]
In **sp** and **rgdal** (I maintain the latter) with regard to changes in coordinate systems representations, I used `warning()` but provided an option to reduce or mute the frequency of warnings appearing after some months. Using **s2** for unprojected coordinates is very new, so certainly requires attention from users, because it changes output, as well as compute times.

**Comment by Nowosad** [comment]
Just a suggestion: @rsbivand would it not be better to add a startup message about new s2 changes? Currently, (some) users are using **s2** operations without knowing that some things have changed. 

They will only get a message (`cat()`) when they try to disable it. I assume that people who will be able to find the `sf_use_s2()` function and disable it, already spent some time understanding the new changes.

**Comment by edzer** [comment]
@mpadge submitted a PR to add a `quiet = TRUE` argument to `sf_use_s2()`. I think it is reasonable to make it easier to suppress its output, but suggest to use `message()` rather than `cat`, so that
```
suppressMessage(sf_use_s2(FALSE))
```
gives you the quiet version. Following @Nowosad's suggestion, maybe the startup message could be changed to
```
Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1; sf_use_s2() is TRUE
```
