### ISSUE TITLE
Returning units makes common operations fail

### ISSUE THREAD

**Issue by DOSull** [r-spatial/sf#1840]
I wonder if it would be possible to include a flag in `st_area` and similar functions so that they not return results with units? Currently

```
> region %>% 
  dplyr::mutate(area = st_area(.)) %>% 
  dplyr::filter(area > 100)
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `area > 100`.
x both operands of the expression should be "units" objects
Run `rlang::last_error()` to see where the error occurred.
```
The problem is clearly stated in the error report, and of course I can do `st_area(area = as.numeric(st_area(.)))` it would just be nice not to have to!

Issues also arise with any derived attributes (such as a density) that make use of the calculated `area` attribute. Often, It would be nice to be able to control this behaviour, and only assign units when required.

**Comment by markolipka** [comment]
I also step into this quite often.

Maybe a simple and comfortable solution could be a kind of coercion with a warning instead of an error in cases when operations need units objects but numerics are provided.
This issue might be rather addressed to units:: package then, right?!

**Comment by edzer** [comment]
My suggestion would be instead of `st_area(area = as.numeric(st_area(.)))` to use `dplyr::filter(area > units::set_units(100, m^2))` in the following expression, so that it is clear for yourself (and everyone else) what you have in mind doing. We argue [here](https://journal.r-project.org/archive/2016/RJ-2016-061/index.html) that _Using units may eliminate a whole class of potential scientific programming mistakes._ Of course such elimination comes at a small cost, but you are both scientists, right?

As a counter example, would you also appreciate that `Sys.time()` would have a flag, say `as_number = TRUE`, or even R having a global flag, to return the number of seconds since 1970-01-01, as a simple and comfortable alternative to `as.numeric(Sys.time())`?

**Comment by DOSull** [comment]
I guess reasonable people can disagree!

Often during data tidying, I'm not so concerned about communicating to others what I'm doing, I just want to filter out small areas, or whatever it might be, and the `units` infrastructure feels like overkill, to the point where I'd prefer to keep everything unit-free so it just stays out of my way! I don't think that makes me less of a scientist, just more just a busy person wanting to get things done...

The current behaviour is particularly annoying in exploratory mode, when I'm just trying to get a handle on my data and simple things like `region %>% filter(area < 10)` fail, because I didn't do `region %>% filter(area < set_units(10, m^2)`.

I understand per Cobb & Moore cited in the paper that "Data are not just numbers, they are numbers with a context", and I also understand that this can help with common errors (like the number of decimal places in m^2 to km^2 conversions), but sometimes context is well known to the only person using the tool, and this stuff feels like it is getting in the way.

In this case, it could be simply a case of assuming the user knows what they are doing and assuming that quantities with units not specified are the same as the comparator, while issuing a warning. But I guess this would a request for the `units` package rather than `sf`

**Comment by jannes-m** [comment]
I can only speak for myself but I think it is not too much of an overhead of writing `set_units()` even in exploratory mode, once you have figured out that's the way to go about units (as you obviously already have), and I also like the benefit of being very clear on the used unit even if I am the only person using the script since I tend to not remember after 6 months which specific area unit has been used for a certain spatial object.

**Comment by aourednik** [comment]
The forceful assignement of units has other consequences, starting with the fact that you cannot do something as common as mapping a population density with geom_sf:

```r
compoly$superficie <- st_area(compoly)
compoly$densite <- compoly$pop/ compoly$superficie
ggplot(compoly) + geom_sf(aes(fill=densite)) 
```
returns:

```
! Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `scale_type.units()`:
! Variable of class 'units' found, but 'units' package is not attached.
  Please, attach it using 'library(units)' to properly show scales with units.
```

If you do as you're told:

```r
library(units)
ggplot(compoly) + geom_sf(aes(fill=densite)) 
```

you still have an error:

```
Error in Ops.units(x, range[1]) : 
  both operands of the expression should be "units" objects
```

Of course, I can solve this by forcefully _removing_ the units tag every time I calculate something

```r
compoly$densite <- (compoly$pop / compoly$superficie)  %>% as.numeric
```

but this is terrible on students that start working with R.

Could you consider _not assigning units_ to sf calculations until the units package stops being psychorigid about all operands having to be units objects (warnings instead of errors), or until the package gets its compatibility straight with the most important packages like ggplot?

**Comment by edzer** [comment]
> Could you consider not assigning units to sf calculations until the units package stops being psychorigid about all operands having to be units objects (warnings instead of errors), or until the package gets its compatibility straight with the most important packages like ggplot?

I don't see how you could do units "a little bit": either you do it, or you don't. You can strip your spatial object from their CRS, or strip area from its units, and teach students that from there on it's just numbers, and the entire responsibility of understanding what the numbers are, or whether addition is meaningful and what multiplication implies, is all up to themselves. I don't think that that is such a bad thing for students to realize.

> or until the package gets its compatibility straight with the most important packages like ggplot?

ggplot is a large and complex code base, and has a lot of reverse dependencies. I think units along axis labels in ggplot2 plots work, thanks to ggforce, and yes it would be great if things worked with the fill thing.
