### ISSUE TITLE
setting number of digits when using st_write to ESRI shapefile

### ISSUE THREAD

**Issue by JacobusS** [r-spatial/sf#1870]
All the numeric fields in the .shp files that I create, using st_write() has an insane number of digits.
I have tried:

- options(digits = 3)
- mutate(across(where(is.numeric), ~ round(., digits = 32))) 
- And even just plain old round(MY_NUMERIC_FIELD, 3)

Nothing seems to work. Am I missing something, is this something in R of SF? 
At the moment I'm using R/sf to writing to shapefile, then use QGIS's refactor tool to fix the fields. But with the multiple files that I create everyday this is not a long-term solution. Any advice would be highly appreciated.

**Comment by edzer** [comment]
You don't provide a reprex, so I can only guess what your problem is.

shapefiles are binary files, and written as such. If you round prior to writing, you loose information. Maybe QGIS will let you control the amound of digits it _shows_?

Rounding to 32 digits does not make sense: 8 byte doubles represent around 16-17 digits only.

**Comment by rsbivand** [comment]
My guess was that the DBF file is the culprit, rather than the SHP file (which all should know is binary, see the specs: https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf), that is DBF as used  on DOS systems late last century. Time for the GeoPackage format, as ESRI themselves stress (long field names, UTF-8. etc.). Anyway,  this is the OGR driver, not **sf**: https://gdal.org/drivers/vector/shapefile.html#vector-shapefile.

**Comment by JacobusS** [comment]
Thanks for the quick response. 
Very interesting, thanks!!
I agree it's the OGR driver that is doing this.

The QGIS tool might changes the DBF file, if I open the refactored shapefile form QGIS in ArcGIS or any other software the digits is correct. 
O how I wish I could just send the files as GeoPackage rather than shapefiles. 
But I'm going to be 100% honest the uptake of GeoPackage is very slow at best and people don't rely use it at all. 
Thanks for the response.

**Comment by rsbivand** [comment]
There are two things that maybe help a bit:
```
library(sf)
nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"))
tf1 <- tempfile(fileext=".shp")
st_write(nc, tf1)
tf2 <- tempfile(fileext=".shp")
st_write(nc, tf2, layer_options=c("RESIZE=YES"))
```
reduces the size of the DBF, but cannot do more than that. In `nc`, many fields are stored as `"double"` but could be `"integer"` (manual intervention):
```
sapply(nc, storage.mode)
storage.mode(nc$CNTY_) <- "integer"
storage.mode(nc$CNTY_ID) <- "integer"
storage.mode(nc$FIPSNO) <- "integer"
storage.mode(nc$CRESS_ID) <- "integer"
storage.mode(nc$BIR74) <- "integer"
storage.mode(nc$BIR79) <- "integer"
storage.mode(nc$NWBIR74) <- "integer"
storage.mode(nc$SID79) <- "integer"
storage.mode(nc$SID74) <- "integer"
storage.mode(nc$NWBIR79) <- "integer"
sapply(nc, storage.mode)
tf3 <- tempfile(fileext=".shp")
st_write(nc, tf3)
tf4 <- tempfile(fileext=".shp")
st_write(nc, tf4, layer_options=c("RESIZE=YES"))
file.size(file.path(tempdir(), list.files(tempdir(), "dbf")))
```
The output needs re-ordering, but the tf4 DBF is smallest - but the fields corresponding to R `"double"` are always `N,24,15` anyway. The `"integer"` fields are resized from `N,9,0` without using the creation option to variable width. To get AREA and PERIMETER to be integer, you'd have to say multiply by 1,000, round, convert to integer storage, and remember the change in metric. Not great, really. RESIZE also thins down string fields, so impacts DBF file size by not grabbing 80 bytes for each field.
