### ISSUE TITLE
Why st-intersection creates micro-polygons while on GIS they are not present?

### ISSUE THREAD

**Issue by bstnmdry** [r-spatial/sf#2109]
Hello I have a problem with st_intersection.

First of all, I'm sorry for my horrible english, I'm french. 

My problem with st_intersection is that it creates some kind of micro polygons when intersecting two .shp layers when it should not. Moreover by intersecting two layers containing only polygons I end up with different geometry on the output layer (LINESTRING, MULTILINESTRING, POINT, MULTIPOINT). Is there a solution to eliminate these biases? 

Thank you in advance for your answers!

**Comment by edzer** [comment]
Hi french, this is not unusual, and essentially a consequence of doing geometry operations with coordinates represented by floating point numbers. You can do several things:
* use `st_set_precision` on your data before intersecting, so that coordinates get (slightly) rounded to a fine grid
* use `st_dimension` to filter out the point (0) or line (1) geometries
* use `st_area` to filter out ares (slivers) with extremely small areas
