### ISSUE TITLE
How to handle the difference between ellipsoidal and spherical computations

### ISSUE THREAD

**Issue by LemonLiTree** [r-spatial/sf#2153]
I just read this article：
https://r-spatial.org/r/2020/06/17/s2.html
i learned , when handling geographic coordinates package sf uses the S2 geometry library for spatial operations.and the difference between ellipsoidal and spherical computations is roughly up to 0.5%;
If I want to do geographic calculations based on the WGS84 coordinate system, it is not accurate to use S2 directly for calculations
so How to handle the difference between ellipsoidal and spherical computations in sf ?

**Comment by rsbivand** [comment]
It depends on your needs. If you are working in precision farming, you will probably anyway use planar geometries with a very well defined underlying datum. If you are handling global data, s2 will be fine (0.5% is not a good expression of the differences). Try it out yourself and see https://r-spatial.org/book/04-Spherical.html.

**Comment by edzer** [comment]
The blog post you refer to does not (yet) refer to `sf_use_s2()`. It only matters when computing with geodetic coordinates (degrees long/lat). For instance:
```r
library(sf)
# Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
a = st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0)))))
a.4326 = st_set_crs(a, 'EPSG:4326')
st_area(a) # R2: "square degrees?"
# [1] 1
st_area(a.4326) # spherical approximation
# 12364036567 [m^2]
sf_use_s2(FALSE)
# Spherical geometry (s2) switched off
st_area(a.4326) # ellipsiodal approximation
# 12308778361 [m^2]
```
For measures (distance, area) switching s2 off leads to ellipsiodal approximations; for transformations (buffer, intersection) or predicates (intersects, covers etc.) switching s2 off leads to using R2 (long/lat as Cartesian, flat space) approximations. The value `1` above was obtained because `a` does not have a coordinate reference system set, and by default `sf` assumes Cartesian coordinates if CRS was not set.
