### ISSUE TITLE
problem with gdal in read_sf/st_read

### ISSUE THREAD

**Issue by tmh12** [r-spatial/sf#2163]
I am trying to read a large and complex feature class from a geodatabase but I have been encountering this warning: `GDAL Error 1: Error occurred in ../../../../gdal-3.6.2/ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp at line 1017` when I try to read the data, and nothing gets read. I am using the most recent version of the sf package with GDAL 3.6.2 with R 4.3.0. When I try to read the same data with sf 1.0-5 and GDAL 3.2.1 with R 4.1.2 I have no issue. I am wondering how to avoid this issue with the updated versions? Unfortunately I am not permitted to provide the data to replicate the issue.

**Comment by rsbivand** [comment]
Please give your operating system and how you installed GDAL in each case. The driver has changed a good deal.

**Comment by tmh12** [comment]
I am using Windows 10 in both cases and GDAL was installed with the sf package

**Comment by rsbivand** [comment]
Please consult https://gdal.org/drivers/vector/openfilegdb.html and see whether you can see the issue. It will be complicated to unpick, as Rtools40 is EOL.

**Comment by tmh12** [comment]
Thanks for the advice, I had a look, but as far as I can tell everything seems to be in order with no obvious issues

**Comment by rsbivand** [comment]
If you could make available (a subset of) your dataset, it could be tested with ogr2ogr or ogrinfo outside R and sf to establish which change - GDAL or sf - is interferring.

**Comment by tmh12** [comment]
Unfortunately I cannot provide any part of this data for security reasons. But it appears to have something to do with the record count. The total data set has just over 1.6 millions records when I split it into 2 halves manually `read_sf` has no trouble reading both halves in to my R session, but when I try to read them all together as 1 set I get the error.

**Comment by rsbivand** [comment]
Can you generate a similar, synthetic data set that replicates the issue?

**Comment by CamilaAchuri** [comment]
I hope this message finds you well. I am currently encountering an issue with the latest version of the sf package (last github version) in R. Specifically, when I attempt to run the example provided in the documentation for the st_read() function using the following code:

```
st_read(system.file("shape/nc.shp", package = "sf"))
```
I immediately receive a "Restoring session" warning, which disrupts the expected behavior of the function.

Here are the details of my system configuration:

R version: 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Operating System: macOS Monterey 12.3.1

I have tried reinstalling the sf package and updating all its dependencies, but the issue persists. It seems to be specific to this combination of R version, platform, and operating system.

Thank you for your attention to this matter. I look forward to your response.

**Comment by rsbivand** [comment]
@CamilaAchuri please start a new issue, you are not reading a filegdb on Windows. You are using macOS, arm64, and Rstudio. 

Please in the new issue report whether sf works properly without Rstudio, and do mention the Rstudio version. Do other packages cause Rstudio to fail?
