### ISSUE TITLE
Error With sf in Sen2r

### ISSUE THREAD

**Issue by Pablocr7** [r-spatial/sf#2168]
I have a problem with sen2r, I'm trying to process  sentinel images with GUI of sen2r, but in the moment of  process them, i have a error with st_list_is_valid, this is the error:
Error in UseMethod("st_is_valid") : 
  no applicable method for 'st_is_valid' applied to an object of class "logical"

**Comment by markolipka** [comment]
Hi,

Without a detailed explanation what you are trying to do and how, nobody here will be able to help you.

Probably, this problem is more related to the sen2r package rather than the sf package.

You should try to provide a few lines of code that illustrate your problem so that others can reproduce it.

**Comment by Pablocr7** [comment]
hi, i am trying to process sentinel images with the sen2r GUI to get the NDVIs, i have the tiles downloaded and i am loading it in sen2r but when i run it in the GUI i get the error i mentioned before, is it because of the sf library

**Comment by edzer** [comment]
To me, the error you reported

> Error in UseMethod("st_is_valid") :
no applicable method for 'st_is_valid' applied to an object of class "logical"

indicates a problem in `sen2r`

**Comment by Pablocr7** [comment]
yes, is a problem in sen2r but i don't understand this error because I can't process the NDVI of the tiles that i have in my pc
