### ISSUE TITLE
sudden `ERROR:  type "geometry" does not exist` when writing to a postgres/postgis db

### ISSUE THREAD

**Issue by lvalnegri** [r-spatial/sf#2339]
Hi, I've used to run this command regularly for a while on a set of a few dozen polygon objects:
```
dbConnect(Postgres(), host = '127.0.0.1', dbname = 'gisdb', user = 'devs', password = Sys.getenv('POSTGIS_DEVS'))
y <- st_read(fn, x, quiet = TRUE)
names(y) <- tolower(names(y))
st_write(y, cn, Id(schema = sn, table = tolower(x)), delete_layer = TRUE)
```
and all has been well until today when I've started to receive:
```
Error: Failed to fetch row : ERROR:  type "geometry" does not exist at character 52
```
the objects `y` are totally valid sf objects, I 've tried a few manually and the results is always that. I can connect to the db as usual and creating a table with a single point feature form terminal works. 
I'm not sure what happened, someone could have updated something? I've asked around, but no one did...

thanks for any help,
Luca

**Comment by rsbivand** [comment]
In order to identify the cause, you need to identify on your (unknown) platform which software component was updated. If none, has any other transaction altered the DB. If PostgreSQL, does the installed version of PostGIS match the new PostgreSQL version, and so on, through the R version and the `sf` version. Once you find which component changed last, there is a chance that the issue is sufficiently narrow for identification. So far, none of this information is present in the issue.

**Comment by lvalnegri** [comment]
> In order to identify the cause...
Thanks Roger for the feedback, I think "something" happended from our side playing with PostGIS, as I tried to use ogr2ogr and the first line after connection is an error `function postgis_version() does not exist`. I'm sorry for the bother, I should have tried outside of R before posting.
