### ISSUE TITLE
Development of an sf Package for Julia

### ISSUE THREAD

**Issue by Jigyasu4indp** [r-spatial/sf#2472]
Hello,
Could you consider developing an sf (Simple Features) package for Julia? This addition would be immensely beneficial to the Julia community, as it would allow for the utilization of sf-style spatial data handling within the Julia ecosystem. Currently, many users rely on R's sf package, and having a native Julia equivalent would streamline workflows, especially for those transitioning from R to Julia.

**Comment by tim-salabim** [comment]
Are you aware of https://juliageo.org/? Specifically GeoDataFrames.jl

**Comment by Ujjwal4CULS** [comment]
I don’t think that GeoDataFrames.jl has plotting capabilities equal to geom_sf for publication purposes, but I could be wrong.

**Comment by tim-salabim** [comment]
`geom_sf` is provided by ggplot2, not sf. Native sf plotting uses base plots. GeoDataFrames.jl also has plotting capabilities AFAICT. https://www.evetion.nl/GeoDataFrames.jl/dev/tutorials/ops/#Plotting

**Comment by evetion** [comment]
Author of GeoDataFrames.jl here, appreciate the link. To be frank, GeoDataFrames currently is but a shadow of the sf package (it's mostly a thin wrapper to read/write vector data using GDAL). 

I think most of sf functionality now exists in some form in Julia (native operations is a different package, as is wellknowngeometry, as is plotting, etc), but it has not been combined into one package. This is partially by design, as we like to compose functionality in Julia, but the main drawback is discoverability. We're aiming to improve that, for example by writing better documentation (https://jl.geocompx.org/ is in progress), and re-exporting some basic things so you don't need to import yet another package (very small utility packages like Extents.jl, GeoFormatTypes.jl).

There are plans to make GeoDataFrames more than just a thin wrapper, and indeed an entry point to spatial vector data in Julia (https://github.com/evetion/GeoDataFrames.jl/issues/81). If you have specific needs or thoughts, feel free to make an issue over there.
