### ISSUE TITLE
Some functions not %>% friendly?

### ISSUE THREAD

**Issue by waynefoltaERI** [r-spatial/sf#447]
I'm a `data.table` man myself, but since `sf` is so tidy-oriented, I'm taking it as an opportunity to see how the other half lives. I may be doing this in a roundabout way, but when I do the following, I must put braces around the last two function calls, which I think is an indication that they're not `%>%` friendly. (I'm turning the internal lines for the US states into something I can `st_transform` to project:

```
m <- map ("state", boundary=FALSE, fill=FALSE, plot=FALSE)
mm <- tibble (x=m$x, y=m$y) %>%
   mutate (group=ifelse (is.na (x), 1, 0)) %>%
   mutate (group=lag (group, 1)) %>%
   filter (!is.na (x))
mm$group[1] <- 1
mm$group <- cumsum (mm$group)

us48i <- mm %>% group_by (group) %>%
   do (geometry=st_linestring(matrix (c(.$x, .$y), ncol=2))) %>% ungroup ()  %>%
   { st_multilinestring (.$geometry) } %>%
   { st_transform (st_sfc (st_segmentize (., 1), crs=longlat), crs=crs) }
```

I really like `sf`, by the way. For my particular use case it, like `sp`, is more complicated than just using `mapproject` on x/y coordinates, but in the long run it offers advantages. (My current project is to plot zip-code-level data in `ggplot` using hexbin to aggregate the data to various scales.)

(As a data.table man, I would add my vote for Issue #428. At a minimum, when I print a data.table, it'd be nice to see the first 10 and last 10 lines -- the usual option, like a dibble's first-10 -- rather than trying to list the first 1000 lines, which scrolls the geographic info off the top.)

**Comment by edzer** [comment]
If your definition of pipe-friendly is that everything should work on a `data.frame` or `tibble` then I agree, but for the kind of low-level thing you're doing this is not going to work, and that was by design; read the `sf` vignettes if you want to learn why. For your second section, a cleaner way would be to `pull` the geometry column and work on that,
```r
us48i <- 
	mm %>% group_by (group) %>%
	do (geometry=st_linestring(cbind(.$x, .$y))) %>% ungroup ()  %>%
	pull(geometry) %>%
	st_multilinestring %>%
	st_sfc(crs = 4326) %>%
	st_segmentize(units::set_units(10, km)) %>%
	st_transform (3857) 
```
or, alternatively
```r
us48i <- 
	mm %>% group_by (group) %>%
	do (geometry=st_linestring(cbind(.$x, .$y))) %>% ungroup ()  %>%
	mutate(geometry = st_sfc(geometry, crs = 4326)) %>%
	st_sf %>%
	st_combine %>%
	st_segmentize(units::set_units(10, km)) %>%
	st_transform (3857) 
```
Wrt your comments on `data.table` #428, I'm still looking forward to see examples of things that don't work with `data.table`, along with explanations of how they should work. The reason that `sf` is tidyverse-friendly is purely because early adopters came with very detailed examples of things that didn't work, with explanations about how they'd expect them to work. Making those things work turned out to be quite  trivial most of the time, but wouldn't have worked without their input.
