### ISSUE TITLE
GeoJSON round-trip fails with time like feature properties

### ISSUE THREAD

**Issue by botanize** [r-spatial/sf#505]
This might be a gdal2 issue. 

`sf` fails to read GeoJSONs written from `sf` with time like fields e.g. "12:00" or "12:00 PM".

```r
library(sf)
a <- st_as_sf(data.frame(time = '12:00', lon = -80, lat = 26.7), coords = c('lon', 'lat'), crs = 4326)
fname <- tempfile(fileext = '.geojson')
st_write(a, fname)
# fails with sf 0.5-4/gdal 2.1.3
st_read(fname)
# works with rgdal 1.2-11
rgdal::readOGR(fname)
```

The contents of the GeoJSON itself:
```js
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "time": "12:00" }, "geometry": { "type": "Point", "coordinates": [ -80.0, 26.7 ] } }
]
}
```

Removing the colon in the time field solves the problem.
```r
# works with colon removed from 'time' field
st_read('{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "time": "1200" }, "geometry": { "type": "Point", "coordinates": [ -80.0, 26.7 ] } }]}')
```

**Comment by edzer** [comment]
But note that `rgdal::readOGR` reads time back as a `factor`. I would recommend to specify time as `POSIXct` in R, and use e.g.
```r
a <- st_as_sf(data.frame(time = Sys.time(), lon = -80, lat = 26.7), coords = c('lon', 'lat'), crs = 4326)
```
which is read back as `POSIXct` by `st_read`.

**Comment by botanize** [comment]
I can fix the read as factor using this:
```r
rgdal::readOGR(fname)
```
What I want is the character string "12:00" to be written as a character string and read as a character string. With that in mind, how would I round-trip it?

**Comment by edzer** [comment]
The field `12:00` is understood by the gdal driver as a time object, of type `OFTTime`.Since R does not have a native time (of day) class, both rgdal (and now sf) treat it as "other", and read it in as string. Padding the time with `:00` must be done by the gdal driver.

A way out of this could be to use class `hms` from the `hms` package to represent time of day, but that would introduce an additional dependency. You could also string process to strip the trailing `:00` if that is the whole point -- after all, the meaning in terms of time of day is correct as you get it now.
