### ISSUE TITLE
Is is possible to save and reuse a spatial index?

### ISSUE THREAD

**Issue by mem48** [r-spatial/sf#546]
My understanding of http://r-spatial.org/r/2017/06/22/spatial-index.html is that the spatial index of the two geometries is created when st_intersects is called and then lost when the function is completed.

I have a function containing a loop that has to repeatedly subset out a small part of two very large sf data frames based on location.  I think that being able to directly access the spatial index would allow me to write faster code.
 
Currently, I'm using a bodge by making my own simple spatial index 

```
# Pseudo Code

grid <- st_make_grid(df1, n = c(100,100), "polygons")
grid_1 <- st_intersects(df1, grid) # which grids are each df1 geometry in?
grid_2 <- st_intersects(grid, df2) # for each grid which df2 geometires are contained within it?

# Loop
for(i in 1:nrow(df1)){
  
  # Select the object of intrest in df1 and then find nearby objects in df2
  df1.select <- df1[i,]
  grid_ids <- grid_1[[k]]
  ids_grid <- unique(unlist(grid_2[grid_ids]))
  df2.select <- df2[ids_grid,]
  
  #Now check for actual intersection between the two objects
  df2.select <- df2.select[df1.select,]

  # Rest of code works on df1.select and df2.select
  
}
```

Creating the grid and two intersections only takes a few seconds, while doing a `st_intersects(df1,df2)` takes several hours due to the size of the datasets.

I suspect that the proper spatial indexes are faster and more precise but I don't see how they can be accessed.

Is it possible to "get to" the spatial index in R and use it within functions?

**Comment by edzer** [comment]
No, you can't. 

Do note that a spatial index is only built on the first argument of `st_intersects`; run time might differ if you revert the arguments (and call `t()` on the resulting object).

**Comment by mem48** [comment]
Thanks for the clarification

**Comment by DavorJ** [comment]
I also think that a spatial index as an attribute to a sf/sfc object would be interesting. Especially since I couldn't find any R packages for this. 

For an unindexed sf/sfc object, the bounding box wouldn't have to be computed, which would speed up loading (cf. [this](http://disq.us/p/27wwf30) comment). An indexed sf/sfc on the other hand would justify the extra time taken to compute the bounding box together with the Rtree index.

Anyway, just a thought.

**Comment by edzer** [comment]
Please feel free to do it and show how well it works!

**Comment by joshthu** [comment]
Firstly: thanks for all this amazing work. I have been using Spatialite extensively for spatial modelling for a few years, but have recently been trying out sf - it is very attractive to carry out all  operations within R, rather than generating SQL statements, running them against the database and retrieving the results.

That said, a couple of questions:

- Is it fair to say that persistent indexes are an advantage that Spatialite has over R/sf?
- Is there a fundamental reason why they could not be implemented in sf (speaking as someone who would not be able to implement it himself even it were possible!)

Thanks

**Comment by edzer** [comment]
> Is it fair to say that persistent indexes are an advantage that Spatialite has over R/sf?

yes.

> Is there a fundamental reason why they could not be implemented in sf (speaking as someone who would not be able to implement it himself even it were possible!)

no.

**Comment by joshthu** [comment]
Thanks for responding. Please forgive the obvious next question.... do you have any plans to implement persistent indexes in R/sf?

**Comment by edzer** [comment]
Not as part of my unpaid maintainer job.

**Comment by joshthu** [comment]
That seems fair enough!
