### ISSUE TITLE
rbind(..., fill=TRUE) fails with 'Error: arguments have different crs'

### ISSUE THREAD

**Issue by yaakovfeldman** [r-spatial/sf#588]
I have some `sf`s that I obtained from openstreetmap. When I `rbind` them together I get an error (understandably) if they have different columns (which is often the case considering the source).

I tried adding `fill=TRUE` to `rbind` but get the error that `Error: arguments have different crs`.

I knew that they had the same crs so I tried (as an experiment) `rbind`ing a `sf` object to itself. With `fill=TRUE`, I still get the error. I even tried on the built in `nc` object:

    > rbind(nc, nc, fill=TRUE)
    Error: arguments have different crs

Is there a better way to combine them? What does the error mean? How can an object have a different crs to itself...

Is this related to https://github.com/r-spatial/mapedit/issues/46 ?

As a workaround, I dropped the columns that were different using `intersect`, and then was able to use `rbind` as normal, but I would prefer to keep all columns.

Thank you for the package, by the way!

**Comment by edzer** [comment]
Neither the base::rbind generic nor the rbind method for `sf` objects have a fill argument; you may be confused by the rbind.data.table method.

What happens is that `TRUE` is seen as another table to be `rbind`-ed, and that fails because it is not of class `sf`.

You could however convert your objects to data.tables, use the data.table rbind method with fill=TRUE, and then convert the result back with `st_sf()`.

**Comment by yaakovfeldman** [comment]
Thank you

**Comment by lago1970** [comment]
Thanks so much for your tip!
