### ISSUE TITLE
sf version of "identify"

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#590]
I'd like to click on a plot and get the feature that that location. Is there a method like "identify" on base plots? 

Something like:

`st_identify = function(features, tolerance, labels,....)`

which would return the index of point or line features within tolerance, or of polygon features clicked inside, adding labels at the click locations (and having some other args like `identify`).

I reckon I could implement this easily for base graphics plots, but I'm seeing so many different plots using tmap and grid graphics with sf objects I'm not sure it would get used (and misused) more than it would work. Is there a "locator" type function for grid plots or tmap that return coordinates in the user space?

Ideas welcome...

**Comment by rsbivand** [comment]
Good idea, maybe @mtennekes could comment? For interactive modes, can the underlying javascript return a coordinate (the values are read out on the top bar)? For static modes, is grid::grid.locator() useful? I'd guess that sf_locator() would need to be a generic method?

**Comment by tim-salabim** [comment]
AFAIK, as soon as you want the identified features be returned to the R console, you need shiny (or some other server connection). `mapedit::selectFeatures` returns the identified features as an sf object.

**Comment by edzer** [comment]
What you could do with an existing base plot is 
```r
identify_features(features_plotted, n = 3)
```
and then use `x <- locator(n)` and return the features of `features_plotted` that intersect with the clicked locations.

**Comment by barryrowlingson** [comment]
identifying on tmap plots might be tricky, because the plotted coordinate system will usually be the CRS of the first "tm_shape" object, but the user might want to identify features from another object added in the plot. Without knowing the CRS of the base plot I don't think its possible. `st_identify` would need another argument for the base CRS or the object with the base CRS if there's a difference.

**Comment by mtennekes** [comment]
Identifying on static tmap plots is not straightforward, but certainly possible. The crs of the last plot can be stored into the hidden environment of the package. Obviously, this function will use `grid::grid.locator`.

**Comment by edzer** [comment]
I committed this in the `use_lwgeom` branch, by accident, will merge into master once lwgeom 0.1-1 compiles on CRAN OSX flavors.

**Comment by dvrbts** [comment]
The proposed identify.sfc does not behave like identify typically does, i.e. to return a vector of ids in the order clicked.  I propose this one instead

identify.sfc <- function(x,n=1) {
	l = locator(n)
        out <- NULL
        for (i in 1:length(l$x)) {
            pt <- st_point(cbind(l$x[i],l$y[i]))
            val <- which.max(st_intersects(x,pt))
            out <- c(out,val)
        }
        out
}

**Comment by edzer** [comment]
afaict, `graphics::identify` does not return ids in the order clicked, bu tin increasing order.

**Comment by dvrbts** [comment]
Hi Edzer.  I'm confused obviously, ?identify says "If ‘pos’ is ‘FALSE’ (the default), an integer vector containing the indices of the identified points, in the order they were identified." but it doesn't seem to be true.  AS you noted, they are returned in increasing order, not the order clicked.   I'll have to dig some more.

**Comment by dvrbts** [comment]
AFAICT the results of graphics::identify differ from the documentation, and as Edzer notes, simply list located points in numerical order, not the order in which they were identified.  If all you are after is an un-ordered set then it makes no difference.  More to the point, however, I guess I was shooting for a map query function, not a point location function.  Borrowing from Edzer's posted code, using  st_intersects() actually produces a point-in-polygon query, not the identification of nodes along the boundary of the polygon.   It seems like it would be quite difficult to use st_intersects() to identify lines or points, and I really wanted a point-in-polygon response anyway.  So probably, I should have used a different function name rather than identify.  

With respect to honoring the order of selection, I still think that it is advantageous.  What I am really after is the row number of the data.frame for a selected polygon so I can get whatever additional information is known about that polygon.  If the function scrambles the order of selection then the reported data (an ordered subset of the original data.frame) are in error.  Perhaps, as in GRASS GIS, it is better to limit the function to identifying a single polygon at a time, but that seems an unnecessary limitation if the order of selection can be maintained.

I apologize for stirring the water unnecessarily, but perhaps others will find an order-honoring point-in-polygon function for sf classes useful in working with polygon-based thematic maps.

**Comment by edzer** [comment]
Your comment makes perfect sense to me; this should return identified feature indexes in order of identification, and `NA` if there was no intersection.

For identifying points, we still might want to pass on a buffer distance, and do the intersection with the buffered points, otherwise they will all be `NA`, typically.
