### ISSUE TITLE
st_as_sf and st_transform methods for bbox

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#739]
Is there any specific reason why `st_as_sf` and `st_transform` do not have methods for `bbox`es?

It would be nice if `st_as_sf(bbox)` returned a `sf` object with 1 feature: the respective (rectangular) polygon.
Also, `st_transform(bbox, crs)` could return the equivalent of `st_bbox(st_transform(as_as_sf(bbox), crs))`.

Especially the latter could be a bit misleading to newcomers tho.

**Comment by tim-salabim** [comment]
You can use `st_as_sfc(bbox)` which makes sense as it is a geometry only. Hence, `st_bbox(st_transform(st_as_sfc(bbox), crs))` should also work.

**Comment by edzer** [comment]
It could, but I still prefer the latter because it is explicit. If you'd do the former, users might be surprised that what you get is not (always) simply the transformed `c(xmin,ymin)` and `c(xmax,ymax)`. Enforcing the latter gives users the opportunity to find out themselves. Implementing the former requires us also to write down such semantics of a `bbox` object, and requires users to read that.

**Comment by adrfantini** [comment]
Yes, I see that it could lead to some confusion. Perhaps an example in `st_bbox`'s manual would aid in discoverability.
