### ISSUE TITLE
Problem with plotting `sf_POINT`

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#755]
`plot()` works well with `sfg` and `sfc` objects, but does not work properly with `sf`. An example is attached:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3

p_matrix = matrix(c(0.5, 1, -1, 0, 0, 1, 0.5, 1), ncol = 2)
p_sfg = st_multipoint(x = p_matrix)
p_sfc = st_cast(st_sfc(p_sfg), "POINT")
p_sf = st_sf(geom = p_sfc)

# works
plot(p_sfg)
```

![](https://i.imgur.com/bpqnunZ.png)

``` r

# works
plot(p_sfc)
```

![](https://i.imgur.com/qEP7cI5.png)

``` r

# does not work
plot(p_sf)
```

![](https://i.imgur.com/hYZMUbs.png)

Created on 2018-05-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mdsumner** [comment]
No attributes, the plot needs something to condition on - not sure that was intended

**Comment by Nowosad** [comment]
Good point Michael. 
I've opened this issue, because the last example had worked in the past. @edzer - is it a bug or a feature?

**Comment by edzer** [comment]
It works when you set
```r
plot(p_sf, col = 1)
```
which is of course not a solution. Right now, `col` is being set to `NA` because that is what you want for polygons that have no attributes (col = 1 would fill them, black).

@mdsumner the thinking was to have `sf` objects without attributes plot just like `sfc` objects.

I think this commit fixes this. 

A next thing to do is also have plot methods for `GEOMETRYCOLLECTION` and `GEOMETRY` not have a default value for `col`, so that polygons get plotted empty (no fill, `NA` as default) but points/lines still have a col (1 as default).
