### ISSUE TITLE
More useful error messages when install fails?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#930]
I often see people post here or in `units` when installation fails (I think I was one of them a while back). 

Usually the problem gets fixed when the user correctly installs dependencies.

Is it feasible to detect an installation failure and give dependency installation recipes for the user's system? Starting with Ubuntu?

**Comment by kendonB** [comment]
While your first comment sounds sarcastic, I believe it is a useful start and would likely prevent 90% of such GitHub/SO issues being raised. I would phrase it as: "Installation failed: please carefully read and follow the installation instructions at <readme_link>".

**Comment by rsbivand** [comment]
Right, sarcastic, I get direct emails on average daily. Some are OK (sys-admins on CentOS clusters who have been asked to install R and rgdal and/or rgeos), others are unwilling to grasp simple instructions. Maybe we also need a guide to software installation for those who don't see the difference between binary and source package installs, such as http://r-pkgs.had.co.nz/package.html#package, though this still doesn't mention configure and external dependencies.

**Comment by edzer** [comment]
I discussed package configuring a few weeks ago with @jeroen  and like the way many of his packages do it, like [here](https://github.com/jeroen/V8/blob/master/configure). In addition to telling you what is wrong they tell you what to do to resolve it (right for probably 99% of those running into it). Might save time for developers too.

**Comment by rsbivand** [comment]
But will this just give people fish fingers, or lead them to see that they must learn to fish? This odd (not standard configure) approach probably isn't cross-platform robust, and you know how many cross checks sf, rgeos and rgdal have to do to accommodate systems with ancient external software versions. However, PRs for **sf** or diffs for `configure.ac` for **rgdal** and **rgeos** on R-Forge would be considered, but need subsequent maintenance too. I don't agree with @jeroen that humorous handholding is always helpful - maybe the problem is that there are multiple installs in different places pulled in by installing something else completely (that is the user has no idea that say an ancient GDAL did get installed). The push-back needs to show people that they'll save their own time later by learning this stuff, after all, it isn't rocket science. I'm not saying install all external dependencies from source, even I don't do that, though I do source installs of first-line stuff.

**Comment by lbusett** [comment]
If I may add my two cents here: if the objective is to save time for developers I agree with @edzer that having some "plain english" error messages related to common cases (e.g., a missing dependency) and how to solve them would be useful. Hoping that users would stay on Windows and/or never use `install_github()` seems unrealistic. This also because I believe that many "newbee"/non-developer Linux users, who need to install from source, may struggle with understanding dependencies, issues about duplicated libraries and error messages.

 I know that well: I did the switch from Windows to Linux 3 years ago, and in the beginning I was constantly needing help from more experienced colleagues, or looking for solutions on SO and the web.  I think a good example of this is #929: I fear that the reported error message can fell like hieroglyphics for non-developers / inexperienced users. Automatically giving them even just a "nudge" in the right direction (when/if possible) could help them learn more quickly what they need, and (hopefully....) save developers from explaining the same stuff to different people. 

I agree with @kendonB that providing an "immediate link" to the README of the package or to https://r-spatial.github.io/sf/#installing in case of installation failures could be a good first move: `sf` installations instructions for dependencies are already reasonably clear (though they could maybe still be streamlined/clarified - @edzer, I could give it a try if you wish). The section concerning problems related with multiple library versions on the system is a different beast, but maybe this is a  less common problem with respect to missing dependencies, that could be dealt with in a FAQ/Wiki/dedicated section of the website. 

HTH, 

 Lorenzo

**Comment by GeraldCNelson** [comment]
As someone on a mac (using Mojave, R v 3.5.2, and Rstudio), I'm having trouble with understanding an error message, or rather what to do about it, when I try to install sf from GitHub (`install_github("r-spatial/sf"`)).  I followed the brew instructions at [https://r-spatial.github.io/sf/#installing](https://r-spatial.github.io/sf/#installing) and was successful as far as I can tell. But am still getting an error, as follows. Get this whether I run from an Rstudio terminal or just a regular one.

I've tried a variety of potential solutions that I found online; eg. make sure I have the latest version of Xcode CLT but they didn't help. The error message from configure `cannot run C compiled programs.`   is not specifically associated with installing sf from source but does seem to be fairly common. 

I can run the binary version of sf from CRAN and will go back to it now (v 0.7-2). I was trying the GitHub version to see why the Help for `left_join` in the documentation that starts with `tidyverse(sf)` says` left_join.sf`.  I have the `tidyverse` library installed. When I use code like `x <- left_join(y, z, b = "a")` I get what I expect. But` x <- left_join.sf(y, z, b = "a")` I get a `could not find function`  message.

```
Downloading GitHub repo r-spatial/sf@master
✔  checking for file ‘/private/var/folders/bv/881_rsvd2kv83c13yywwc_xh0000gp/T/RtmpKXI711/remotesf5031ed6d9d5/r-spatial-sf-ee52448/DESCRIPTION’ ...
─  preparing ‘sf’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘sf_0.7-3.tar.gz’
   
Installing package into ‘/Users/gcn/Library/R/3.5/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
configure: CC: /usr/local/opt/llvm/bin/clang -fopenmp
configure: CXX: clang++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.0
checking GDAL version >= 2.0.0... yes
checking for gcc... /usr/local/opt/llvm/bin/clang -fopenmp
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/var/folders/bv/881_rsvd2kv83c13yywwc_xh0000gp/T/RtmpHwwqXx/R.INSTALL126fe3901a9e6/sf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
ERROR: configuration failed for package ‘sf’
* removing ‘/Users/gcn/Library/R/3.5/library/sf’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/bv/881_rsvd2kv83c13yywwc_xh0000gp/T//RtmpKXI711/filef5032d0a25bd/sf_0.7-3.tar.gz’ had non-zero exit status
```
The contents of the folder /private/var/folders/bv are 
```
GCN-MacBook-Pro-7:881_rsvd2kv83c13yywwc_xh0000gp gcn$ ls -l
total 0
drwxr-xr-x@  13 gcn  staff   416 Dec 30 09:50 0
drwx------@  48 gcn  staff  1536 Dec 30 09:43 C
drwx------@ 140 gcn  staff  4480 Dec 30 10:12 T
drwxr-xr-x@   3 gcn  staff    96 Jun 18  2018 TWDDriveUtilityHelper.app
```

**Comment by rsbivand** [comment]
Simply install the binary **sf** from CRAN, unless you both know what you are doing and need extra GDAL drivers that you have built into your GDAL installation and you have confirmed are not in the CRAN **sf** binary. The test WARNING for **sf** on CRAN at https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/sf-00check.html is only caused by pandoc, and does not affect the running of **sf** itself. 

If you can use the CRAN release, do so always. Working around source installation oddities is not a good use of maintainer time. `devtools::install_github()` should not be used on packages with complex system requirements in any normal production settings on Windows or OSX. If you are in sufficient command of your system to provide PRs to the installation instructions after debugging to issue yourself, please do so.

**Comment by edzer** [comment]
To the original problem of @GeraldCNelson : you never need to call `left_join.sf`, it is sufficient to call `left_join` when its first argument is an object of class `sf`. If you must call it (as of: for debugging purposes) use `sf:::left_join.sf`. I agree it is confusing that the docs mention this function, rather than the generic that should be called.

**Comment by GeraldCNelson** [comment]
As a preface, I really like the approach sf takes to spatial data! My comments were a. in response to discussion about how to make error messages clear and b. because the help text that wasn't very helpful about what what left join to use. There is a learning curve to achieve productive use of sf and I'm on the lower part of that curve.
