### ISSUE TITLE
Add check if file.exists() for st_read( )

### ISSUE THREAD

**Issue by angela-li** [r-spatial/sf#967]
Would it be possible to do an early check/stop for if a file doesn't exist for st_read? The error message:

> Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : Open failed.

doesn't tell you if you've done something silly like given the wrong directory path to a file (as shown in #608). Adding an early check with `file.exists()` for `st_read` could provide a more informative error message like "File does not exist. Perhaps you have the incorrect file path?"

I'm speaking as someone who spent far too long trying to figure out what was wrong with my installation of `sf`, when it just turned out I'd made a typo in the file path 😆

**Comment by edzer** [comment]
That sounds welcome but may not be trivial: many data sources do not refer to files, but for instance to tables in a database; for some formats multiple files are written. 

Alternatively you could make it a habit to use `write_sf` which tries to overwrite by default: this is also the default R behaviour e.g. with `write.csv` and so on.

**Comment by angela-li** [comment]
Right, this might not be worth the hassle. I'm thinking of `read.csv` for example, where if you read a file that doesn't exist:

> read.csv("fake.csv")

You get the useful error:

> In file("fake.csv", "rt") :
  cannot open file 'fake.csv': No such file or directory

As versus when you use `sf` to read a file that doesn't exist:

> st_read("fake.shp")

You get a less helpful error message for the user:

> Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Open failed.

Which leads to questions like: _Why did the open fail? Is something wrong with my `sf` installation? Should I try to reinstall GDAL? Should I post an issue on the `sf` repository and wait for the maintainer to get back to me?_ 😆 ...most of which could potentially be resolved with a different error message.

I understand if this isn't a top priority, but it's something I've noticed a few times in my use of the package, and think it would help new users of `sf` be able to better debug their work!

**Comment by edzer** [comment]
I fully agree, I'm just saying that it is not as trivial as just putting an "if file.exists()" before something, and someone needs to code, test, and maintain it.

If we would go the `read_csf` path, we could add `st_read_gpkg`, `st_read_shapefile` and some 100 others, and equip each of them with proper error message mechanisms. "Luckily" we have GDAL that takes care of the file format / data source mess, at the cost of exactly the issue you raise.
 
What do you think of the suggestion to advocate using `read_sf` / `write_sf` instead of `st_*` (taking a risk that someone deletes files inadvertedly, or removes tables from a database)?

**Comment by edzer** [comment]
I like it!

**Comment by rsbivand** [comment]
**rgdal** has in `ogrIngo()` and `readOGR()`: "Cannot open data source" for dsn= that do not exist, and when the dsn= includes the full file path (an innovation to make things easier following **sf** that probably goes on the wrong side of easy). It says "Empty dsn" when `nchar(dsn) == 0L`, and "Cannot open layer" when the layer= is not found. Keeping the DSN visible is a good thing, and not calling it a file is also a good thing. The proposed help message should first direct the unhappy user to the help page (but in a roxygen world, help pages tend to be less detailed and explanatory), and its examples. Pointing to `file.exists()` isn't in general helpful, especially when the typical error (especially in RStudio) is not checking where the input data are in relation to the working directory. So my class advice is usually: do you see what you are looking for in `list.files()`? Which directory is it in? Should you consider pointing dsn= at the place where the data is?

**Comment by lbusett** [comment]
@rsbivand
 I see your point(s). However, I still think that there is value in (explicitly) pointing out to the user that the first thing he should (in my opinion) do in case of "failure on open" is to check that the path provided as `dsn` is correct. This also because trying to open a _something_ from their file system probably covers 95% of usage scenarios for beginner/intermediate users. 

Therefore, although I agree that the wording can be improved/tweaked, I believe that issuing a more "verbose" error message may help. 

Here is a modified proposal/example, somehow incorporating some of @rsbivand points.

``` c
Rcpp::stop("Open failed for dsn: <---->\n.
See examples in `?st_read()`
If you are trying to open a _something_ from your file system, make sure that the path you are passing as `dsn` to `st_read()` (or `read_sf()`) is correct (beware of relative paths - try checking `list.files(dirname(your_dsn))`.\n;
If you are trying to open a table within a DB or a layer within a folder make sure of the above, and also that the table/layer you are trying to access exists (e.g., using `st_layers(your_dsn)`.\n");
```

@edzer / all
- Would it be possible / make sense to "paste" the dsn passed by the user where I put <----> (would not know how to do that on the Cpp side, sorry)
- Not sure at all about "wording" in the second paragraph, but just as an example - Note that I am ignoring possible issues concerning  DBI connections, which I think are/should be dealt with in `st_read.DBIObject`. 
- As far as I can see from examples/test/documentation, when going through the `st_read.character` route the `dsn` must be either 
    1. a file name (maybe corresponding to a "DB" such as `test3.sqlite` in the test data - BTW: what is the "proper" way to refer to those kind of "files"? DB? DB files?), 
     2.  a folder name (such as in `st_read(system.file("shape", package="sf"), "nc")`), or 
     3.  a geojson string. 

Therefore (ignoring geojson for simplicity), when trying to access a particular layer it is sufficient to check for correctness of the `dsn` path, and for existence of the layer within that "path". Is that right, or there are other possibilities?  

  HTH.

**Comment by edzer** [comment]
@lbusett I now see, in a location where `foo` does not exist:
```r
> st_read("foo")
Cannot open data source foo
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Open failed.
```
and I don't see the point of repeating `foo` after `Open failed.`. Or is twice better than once? I suggest we leave out the entire last two error message lines.

I'm all in favor of a longer, helpful error message. Should we for instance suggest the user to try to open the datasource with `gdalinfo` or `QGIS`, in case (s)he  is convinced it exists?

**Comment by edzer** [comment]
Please reopen if someone sees a clear and simple solution here - I don't.
